name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          source-url: https://nuget.pkg.github.com/kolekt.Data/index.json

      - name: Build solution and generate NuGet package
        run: |  
          cd kolekt.Data/kolekt.Data
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./kolekt.Data/kolekt.Data/out/*.nupkg --skip-duplicate --no-symbols true
