name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Build solution
        working-directory: ./kolekt.Data
        run: dotnet build --configuration Release	

      - name: Pack kolekt.Data
        working-directory: ./kolekt.Data
        run: dotnet pack -c Release -o nupkgs

      - name: Push generated package to GitHub registry
        working-directory: ./kolekt.Data
        run: dotnet nuget push "nupkgs/kolekt.Data.*.nupkg" -s "https://nuget.pkg.github.com/pygmypenguin/index.json" -k %GITHUB_TOKEN%
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
