name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build solution
        run: dotnet build --configuration Release
        working-directory: ./kolekt.Data
      
      - name: Pack kolekt.Data
        run: dotnet pack -c Release  -o nupkg
        working-directory: ./kolekt.Data

      - name: Push generated package to GitHub registry
        working-directory: ./kolekt.Data
        run: dotnet nuget push "bin/Release/netstandard2.0/kolekt.Data.*.nupkg" -s "https://nuget.pkg.github.com/pygmypenguin/index.json" -k $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
